[package]
name = "ra-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Wasm / WebGL2 绑定；产出 `@game-gpt/red-alert2-unknown-wasm32`"

publish = false

[lib]
crate-type = ["cdylib", "rlib"]
name = "ra_wasm"

[dependencies]
ra-types = { workspace = true }
ra-engine = { workspace = true }
ra-renderer = { workspace = true }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
