[package]
name = "ra-adaptor-phobos"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Phobos / 心灵终结 3 等内容布局资源表"
keywords = ["phobos", "mental-omega", "red-alert-2", "adaptor"]
categories = ["game-development"]
publish = false

[dependencies]
ra-types = { workspace = true }
