[package]
name = "ra-webui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Wasm / WebGL2 壳"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ra-types = { workspace = true }
ra-engine = { workspace = true }
ra-renderer = { workspace = true }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
