[package]
name = "ra-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "wgpu 渲染（原生 + WebGL2）"

[dependencies]
ra-types = { workspace = true }
ra-session = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }

