[package]
name = "ra-assets"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Westwood 格式解析"

[dependencies]
ra-types = { workspace = true }
blowfish = { workspace = true }
byteorder = { workspace = true }
num-bigint = { workspace = true }
oak-ini = { workspace = true }
