[package]
name = "ra-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "wgpu 渲染（原生 + WebGL2）"

[dependencies]
ra-types = { workspace = true }
ra-engine = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ra-map = { workspace = true }

# 拉齐 `gpu-allocator` 与 `wgpu-hal` 的 `windows` 版本（DX12 子分配类型必须一致）。
[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", default-features = false, features = [
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
] }

