[package]
name = "ra-adaptor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "版本探测与资源表装配"

[dependencies]
ra-types = { workspace = true }
ra-adaptor-ra2 = { workspace = true }
ra-adaptor-yuri = { workspace = true }
ra-adaptor-phobos = { workspace = true }
